<a href="https://colab.research.google.com/github/Laurie-design/learning-data-science/blob/main/Index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("aimee")


aimee


Pour calculer la moyenne

In [ ]:
import numpy as np
revenu=[100, 2000,3000,4000]
revenu_array = np.mean(revenu)
revenu_array

np.float64(2275.0)

## Pour afficher des zéros sur la diagonale

In [ ]:
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##on aura 0-20 avec des pas de 2

In [ ]:
array_arrange=np.arange(0,20,2)
array_arrange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##On aura 100 éléments avec des virgules c-à-dire(1, 1.1919191919 - 20)

In [ ]:
array_linspace = np.linspace(1,20,100)
array_linspace

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

## pour accéder à un indice du tableau

In [ ]:
revenu_array=[100, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array[2]

np.int64(3000)

## Pour afficher le type des éléments du tableau

In [ ]:
import numpy as np
revenu=[100, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array.dtype

dtype('int64')

## Pour modifier une valeur dans le tableau

In [ ]:
import numpy as np
revenu=[100, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array[1] = 2500
revenu_array

array([ 100, 2500, 3000, 4000])

## Pour afficher plusieurs éléments du tableau

In [ ]:
import numpy as np
revenu=[100, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array[0:4]

array([ 100, 2000, 3000, 4000])

##Pour afficher les 2 premiers éléments du tableau

In [ ]:
import numpy as np
revenu=[100, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array[:2]


array([ 100, 2000])

##Pour afficher les 2 derniers éléments du tableau

In [ ]:
import numpy as np
revenu=[100, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array[2:]


array([3000, 4000])

##Pour afficher un élément sur deux

In [ ]:
import numpy as np
revenu=[100, 2000]
revenu_array=np.array(revenu)
revenu_array[::2]

array([100])

##Si le pas est négatif, le tableau est inversé

In [ ]:
import numpy as np
revenu=[100, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array[::-1]


array([4000, 3000, 2000,  100])

In [ ]:
##afficher selon une condition

In [ ]:
revenu=[1000, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array[revenu_array < 2000]

array([1000])

In [ ]:
revenu=[1000, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array[(revenu_array > 1000) & (revenu_array < 3000)]

array([2000])

##pour remplacer les éléments inférieur à 2000 par 100

In [ ]:
revenu=[1000, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array[revenu_array > 2000] = 100
print(revenu_array)

[1000 2000  100  100]


## Obtenir la dimension d'un tableau

In [ ]:
revenu=[1000, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array.shape

(4,)

##min et max

In [ ]:
revenus_array.max()
revenus_array.min()

##Accéder à l'indice de l'élément minimum du tableau

In [ ]:
revenu=[1000, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array.argmin()

np.int64(0)

##ordre croissant

In [ ]:
revenu=[10000, 2000,3000,4000]
revenu_array=np.array(revenu)
revenu_array.sort()
print(revenu_array)

[ 2000  3000  4000 10000]


##Somme

In [ ]:
revenu_array.sum()

np.int64(3200)

`*** Tableaux à deux dimensions (3 lignes 2 colonnes) ***`

In [ ]:
Tab = np.array([[1,2], [2,3],[4,5]])

## Un tableau 3 lignes 5 colonnes rempli de 1

In [ ]:
import numpy as np
tab_ones = np.ones((3,5))
tab_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Un tab 6*3 pour remplir les valeurs aléatoires comprises entre 0 et 1

In [ ]:
import numpy as np
tab_random = np.random.random((6,3))
tab_random

array([[0.64955277, 0.23768393, 0.32843075],
       [0.20747325, 0.5328467 , 0.84483985],
       [0.9324875 , 0.61635956, 0.23652174],
       [0.97919783, 0.27432185, 0.15194203],
       [0.06896569, 0.4879835 , 0.99478996],
       [0.6574899 , 0.48427676, 0.70814031]])

# un tableau de 3x3 rempli de valeurs aléatoires entières, comprises

In [ ]:
tab_randint = np.random.randint(1,10, size=(3,3))
tab_randint

array([[3, 3, 8],
       [8, 8, 5],
       [7, 8, 8]])

## Tableau à plusieurs dimensions

In [ ]:
import numpy as np
tableau = [[1000,100,10],
[2000,200,20],[3000,300,30],[4000,400,40],[5000,500,50]]
tableau_array = np.array(tableau)
tableau_array

array([[1000,  100,   10],
       [2000,  200,   20],
       [3000,  300,   30],
       [4000,  400,   40],
       [5000,  500,   50]])

##accéder indice de la première ligne, première colonne

In [ ]:
tableau_array[0,0]


np.int64(1000)

##Tous les informations sur le premier client

In [ ]:
tableau_array[0,:]

array([1000,  100,   10])

## Les informations d'une colonne entière par exemple l'age qui est 2

In [ ]:
tableau_array[:, 2]

array([10, 20, 30, 40, 50])

##les clients qui ont 25 ans ou moins

In [ ]:
tableau_array[tableau_array[:, 2] <= 25]

array([[1000,  100,   10],
       [2000,  200,   20]])

##Revenu supérieur à 2000

In [ ]:
tableau_array[tableau_array[:, 0] > 2000]

array([[3000,  300,   30],
       [4000,  400,   40],
       [5000,  500,   50]])

In [ ]:
fred= [6000,  600,  60]
np.vstack((tableau_array, fred))

array([[1000,  100,   10],
       [2000,  200,   20],
       [3000,  300,   30],
       [4000,  400,   40],
       [5000,  500,   50],
       [6000,  600,   60]])

In [ ]:
import numpy as np
b = np.array([[[1, 2],[4, 5]],

        [[6, 7],[8, 9]],

        [[10, 11],[12, 13]]])
b

array([[[ 1,  2],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13]]])